use_frameworks!

platform :ios, '9.0'

target 'SwiftyLocalize_Example' do
  pod 'SwiftyLocalize', :path => '../'

  target 'SwiftyLocalize_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
